apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mq-quarkus-app-dev
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: applications
  source:
    path: 1-apps/instances/namespace-dev/mq-quarkus-app
    repoURL: https://github.com/patrocinio/multi-tenancy-gitops.git
    targetRevision: demo-mq
    helm:
      valueFiles:
      - values.yaml
  syncPolicy: {}
