apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespace-prod
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  project: infra
  source:
    path: 3-infra/namespaces/prod
    repoURL: https://github.com/patrocinio/multi-tenancy-gitops.git
    targetRevision: demo-mq
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
